# Generated by Django 4.2.4 on 2023-08-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default=2, upload_to='profile'),
            preserve_default=False,
        ),
    ]
